#import "macros.typ": *
#import "conf.typ": *

#heading("Conclusion", level: 1, supplement: "Chapter") <ch_conclusion>

After 30+ years of intense theoretic development, the most advanced end-to-end pipeline we have for utilizing potential quantum computers beyond the capabilities of classical computers is the simulation of quantum systems. Factoring large integers via Shor's algorithm is one provable advantage, assuming standard complexity theoretic conjectures such as `BQP` $!=$ `BPP`, but the advent of lattice-based cryptosystems implies that using quantum computers solely for factoring integers has decreasing utility as the time to reach thousands of logical qubits grows. Many other provable end-to-end quantum speedups, such as Grover's algorithm for unstructured search or Brandao's Semi-Definite Program solver, only offer quadratic improvements over classical techniques. Evidence suggests that these speedups would have to be applied to unfeasibly large instance sizes in order for these speedups to provide an incentive to build a quantum device. Recent efforts have also explored larger polynomial improvements, such as the quadratic improvement for planted noisy $k$XOR problem @schmidhuber2024quarticquantumspeedupsplanted, but progress remains sparse. There exist other exponential speedups for problems such as Glued Trees traversal or Sunflower graph traversal, but these problems are relatively contrived and have yet to find many real world instances. Despite this lack of applicability, they serve as important guideposts for demonstrating new ways for quantum computers to beat classical algorithms and can inform future quantum algorithm design. The most difficult to analyze speedups are those that rely only on existing classical algorithms, such as normalized Betti number estimation for clique homology @berry2024analyzing, optimization, and linear systems solving.

In this thesis, we presented two new quantum algorithms that can be added to the quantum simulation pipeline. The first is an extension of product formulas to include both random and deterministic sections. We were able to provide generic conditions on when these composite simulations can provide advantages over their constituent methods. We find that systems where the strength of the Hamiltonian terms decays exponentially, i.e. if $H = sum_i H_i$ then $norm(H_i) prop 2^(-i)$, have a relatively large parameter window for improvement. This conclusion was verified numerically for small systems. Further, this algorithm was extended to imaginary time evolution and provides new avenues for improving classical estimations of quantum observables.

The second contribution we make is an algorithm for preparing thermal states $e^(-beta H) / tr(e^(-beta H))$ on a quantum computer. This algorithm assumes access to the Hamiltonian only via time evolution operators $e^(i H t)$ and adds only a single ancilla qubit. At a high level, our technique works by randomizing over all possible interaction terms that could be present between this ancilla qubit and the system of interest. By randomly choosing the energy gap of the Hamiltonian dictating the time evolution of the ancilla qubit we can rigorously show that the thermal state is an approximate fixed point at finite inverse temperature $beta$ if no knowledge of the Hamiltonian spectrum is assumed. We can show that the thermal state is the unique fixed point exactly in the ground state limit ($beta -> oo$) or if the eigenvalue differences of $H$ are known. Remarkably, we are able to bound the number of interactions, the coupling strength, and the time per interaction needed in order to thermalize the system state to within trace distance $tilde(O)(epsilon)$ of the thermal state.

Taken as a whole, this thesis provides a blueprint for compiling quantum circuits to study quantum systems in thermal equilibrium. We do so while providing an extremely rigorous guarantee of the accuracy of the output of the algorithm and for very generic systems. The only requirements we make on the system are non-degenerate eigenvalues, which can most likely be lifted with more careful spectral computations in the ground state limit. In regards to the knowledge of the spectrum we only require a bound on the spectral norm of the Hamiltonian, as this allows us to sample uniformly from a distribution containing all of the eigenvalue differences
