#import "macros.typ": *
#import "conf.typ": *

#heading("Preparing Thermal Quantum States", level: 1, supplement: "Chapter") <ch:thermal_state_prep>
Thermal states of the form $e^(-beta H) / cal(Z)$ are ubiquitous in physics. These are the states that we believe physical systems take whenever they are cooled (or heated) to an inverse temperature of $beta$. They are typically used to estimate observables $O$ of interest in physically relevant states, oftentimes of the form $angle.l O angle.r_beta = tr(O e^(-beta H)/ cal(Z))$. These observables could be anything from dipole moments, magnetizations, or two body correlators. Classically these states correspond to the canonical ensemble, a distribution over phase space that tells us the probability of finding a particle at a particular position and momentum when it is in thermal equilibrium. This is not an issue classically, as we have many proofs outlining when systems are ergodic, meaning that the infinite time average is equal to the phase space average.

For quantum systems, however, such results are pretty much nonexistant. One of the first issues one has to deal with is that in a closed quantum system the evolution operator is unitary, meaning that not only is the energy conserved but the distance between two input states is preserved throughout the dynamics. A system $epsilon$ far away from thermal equilibrium at the beginning will remain $epsilon$ far away throughout the entire duration of the evolution. This is not what is observed in practice, as a quantum system placed in a dilution refrigerator will eventually cool down to the temperature of the fridge.

To resolve this apparent discrepancy physicists have settled on three main approaches: the Eigenstate Thermalization Hypothesis (ETH), Linbladian based evolutions, and the Repeated Interactions (RI) framework. ETH studies thermalization without giving up the notion of a closed quantum system. In this framework the system is taken to be large, as in thermodynamically large, and thermalization is observed whenever one considers the state of a single particle or a single _local_ observable. In chaotic systems these observables can be rigorously shown to appear as if they came from the thermal average $e^(-beta H_"local") / cal(Z)_"local"$, but showing that similar techniques work for non-chaotic systems is a major open question. In fact, the existance of many-body localization serves as a counterexample to a universal ETH, but the existance of these phases of matter in the real world, along with the validity of ETH in general, are heavily debated.

The second approach based on Linbladian schemes abandons the notion of a closed quantum system and instead studies only the effect of the environment on the system. This is a valid idea, as we know from basic quantum information theory that _any_ channel on a system can be mimicked with only a quadratically larger Hilbert space. This means that even the effects of an infinitely large environment can in principle be simulated on finite sized quantum devices. This is the approach taken by @davies1974markovian. Some of the downsides to this approach is that the specific models used for the environment typically make strong assumptions, such as weak coupling, Markovianity, or an infinite number of degrees of freedom, which can break down in specific scenarios.

The last approach is the Repeated Interactions framework which is somewhat of a hybrid of the two previous formalisms. The RI prescription does not abandon the notion of closed quantum systems but instead opts to directly simulate the environment via very small added degrees of freedom. The most straightforward example is to imagine a single photon $gamma$ drawn from some black-body thermal spectrum. This single photon then interacts with the system of interest for a brief period, only to then fly off and never interact with the system again. We then can take a new photon from this thermal background and interact with the system again, but with a refreshed photon. The idea is that by repeating this over and over, if the interaction is properly chosen, the many photons can collectively thermalize the system. The main drawback with this approach is that not only does a model for the environment need to be chosen, but physically realistic interactions need to be inserted in order for the system to converge to the thermal state. Existing RI results have shown that single spin environments are sufficient to thermalize single spin systems, or at the largest a three level system.

In this chapter we explore how to lift these restrictions on the RI framework through a randomized interaction approach. The resulting dynamics are not unitary but instead mixed unitary. We show how to analyze this channel in a weak-coupling regime, which is effectively a Taylor Series with respect to a coupling constant $alpha$. This expansion then reveals a Markov chain underlying the resulting channel on the system. By using basic tools from Markov Chain analysis we can then compute the fixed points of the map and bound the number of interactions needed to converge to the fixed point. By showing that the thermal states are the unique fixed points we can then prove thermalization. The beauty of our technique is that it works for any non-degenerate system with or without knowledge of the eigenvalues of the system, although without eigenvalue knowledeg we are only able to show that the thermal state is an approximate fixed point for finite $beta$ but exactly fixed in the limit $beta -> oo$.

The rest of this chapter is organized as follows. In @sec_tsp_intro we briefly discuss related works in quantum algorithms and provide a summary of the main technical results. In @sec_tsp_weak_expansion we develop the weak-coupling expansion and provide necessary analysis about the underlying Markov chain. In @sec_tsp_oscillator we then take these results and show how to use them to prepare thermal states for single qubit systems and for truncated harmonic oscillators. This section can be viewed as a warmup to the more general results contained in @sec_tsp_generic_sys, but we present the results separately as they utilize slightly different techniques and are more readily comparable to existing approaches. In @sec_tsp_generic_sys we study generic systems from two perspectives, one in which no eigenvalue knowledge is present and the other in which eigenvalues are known. Finally we include a discussion on interpretations of these results and possible extensions in @sec_tsp_discussion.

== Related Work and Main Results <sec_tsp_intro>

== Weak Coupling Expansion <sec_tsp_weak_expansion>

== Single Qubit and Truncated Harmonic Oscillator <sec_tsp_oscillator>

== Generic Systems <sec_tsp_generic_sys>

== Discussion <sec_tsp_discussion>
